{{- range $app := .Values.applications }}
{{- if and (eq $app.enabled true) (eq $app.name "hoverfly") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $app.project | default "default" }}

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io/v1
    kind: Route
    jsonPointers:
    - /spec/host/
    - /status/ingress/

  source:
    repoURL: {{ $app.source | default "https://github.com/helm/charts" }}
    targetRevision: {{ $app.revision | default "master" }} 
    path: {{ $app.path | default "incubator/hoverfly" }}

    helm:
      releaseName: {{ $app.name }}

      values: |
        image:
          repository: docker.io/spectolabs/hoverfly
          tag: v1.1.1
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          externalAdminPort: 8888
          adminPort: 8888
          externalProxyPort: 8500
          proxyPort: 8500
        healthcheckEndpoint: /api/health
        hoverflyFlags:
        # resources:
        #   limits:
        #     cpu: 0.2
        #     memory: 200Mi
        #   requests:
        #     cpu: 0.1
        #     memory: 100Mi
        openshift:
          route:
            admin:
              enabled: true
              hostname: ""
            proxy:
              enabled: true 
              hostname: ""

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.destination }}

{{ end }}