ignoreHelmHooks: false

#  if using the rh-gitops operator and you want to change the location for the ArgoCD instance to be deployed to:
# It's defaulted to labs-ci-cd on the chart anyways
namespaces:
 - labs-ci-cd

# adding your secrets for git access or other repository credentials
secrets:
  - name: git-auth
    username: 'DarkDragonEl'
    password: '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'
    sshPrivateKey: ''

argocd_cr:
  repositoryCredentials: |
    - url: https://github.com/DarkDragonEl/gitops-infra
      type: git
      passwordSecret:
        key: password
        name: git-auth
      usernameSecret:
        key: username
        name: git-auth
