
applications:
  - name: nexus
    enabled: true
    source: https://github.com/rht-labs/ubiquitous-journey
    source_path: charts/ubiquitous-journey
    source_ref: master
    valueFiles:
    - apps/nexus/values.yaml
