{{- if .Values.applications }}
{{- range $app := .Values.applications }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: {{ $app.name }}
spec:
  destination:
    namespace: {{ $app.destination }}
    server: {{ $app.cluster_api | default "https://kubernetes.default.svc" }}
  project: {{ $app.project | default "default" }}
  source:
    helm:
      releaseName: {{ $app.name }}
{{- if $app.valueFiles }}
      valueFiles: 
{{- toYaml $app.valueFiles | nindent 8 }}
{{- end }}
{{- if $app.values }}
      values: |
{{- toYaml $app.values | nindent 8 }}
{{- end }}
    path: {{ $app.source_path }} 
    repoURL: {{ $app.source }}
    targetRevision: {{ $app.source_ref | default "master" }}
{{- if $app.sync_policy_automated }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true
{{- end }}      
{{- if $app.ignore_differences}}
{{ toYaml $app.ignore_differences | indent 2 }}
{{- end }}    
{{- end }}
{{- end }}
{{- end }}
